services:
  python:
    container_name: python_dev
    build:
      dockerfile: ./.devcontainer/Dockerfile.python_dev
      context: ../
    volumes:
      - ../:/python_dev/
    tty: true
    extra_hosts:
      - "host.docker.internal:host-gateway"
